name = "cloudflare-webhook"
main = "src/index.ts"
compatibility_date = "2026-07-29"

[vars]
SITE_URL = "https://cloudflare-webhook.tyansaku3325.workers.dev"

[triggers]
crons = ["0 23 * * *"]
[[d1_databases]]
binding = "DB"
database_name = "zero-capital-insight-db"
database_id = "99ef2162-afd8-459a-87eb-d197127528e2"
