-- Add persistent pipeline execution, idempotency, lease, and notification state.
-- This migration is additive and keeps existing curation_logs rows unchanged.
-- Rollback is a reviewed forward migration; do not edit this file after release.

CREATE TABLE pipeline_runs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  execution_id TEXT NOT NULL UNIQUE,
  idempotency_key TEXT NOT NULL UNIQUE,
  trigger_type TEXT NOT NULL,
  scheduled_for TEXT,
  status TEXT NOT NULL DEFAULT 'running',
  stage TEXT NOT NULL DEFAULT 'gemini',
  article_id INTEGER,
  attempt_count INTEGER NOT NULL DEFAULT 0,
  notification_status TEXT NOT NULL DEFAULT 'pending',
  notification_attempt_count INTEGER NOT NULL DEFAULT 0,
  error_code TEXT,
  error_http_status INTEGER,
  error_retryable INTEGER NOT NULL DEFAULT 0,
  error_summary TEXT,
  lease_expires_at TEXT NOT NULL,
  started_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  saved_at TEXT,
  notified_at TEXT,
  completed_at TEXT,
  failed_at TEXT
);

CREATE INDEX idx_pipeline_runs_status_updated_at
  ON pipeline_runs (status, updated_at);

CREATE INDEX idx_pipeline_runs_notification_updated_at
  ON pipeline_runs (notification_status, updated_at);

CREATE INDEX idx_pipeline_runs_trigger_scheduled_for
  ON pipeline_runs (trigger_type, scheduled_for);

ALTER TABLE curation_logs ADD COLUMN pipeline_run_id INTEGER;

CREATE UNIQUE INDEX idx_curation_logs_pipeline_run_id
  ON curation_logs (pipeline_run_id)
  WHERE pipeline_run_id IS NOT NULL;
