-- Add SEO article metadata without changing existing article content or pipeline state.
-- Existing rows remain readable as legacy records through the DEFAULT values below.
-- Rollback is a reviewed forward migration; do not edit this file after release.

ALTER TABLE curation_logs ADD COLUMN title TEXT;

ALTER TABLE curation_logs ADD COLUMN description TEXT;

ALTER TABLE curation_logs ADD COLUMN body_markdown TEXT;

ALTER TABLE curation_logs ADD COLUMN category TEXT NOT NULL DEFAULT 'uncategorized'
  CHECK (category IN (
    'ai-automation',
    'saas-cloud',
    'security-governance',
    'engineering-infrastructure',
    'dx-organization',
    'marketing-cx',
    'uncategorized'
  ));

ALTER TABLE curation_logs ADD COLUMN published_at TEXT;

ALTER TABLE curation_logs ADD COLUMN updated_at TEXT;

ALTER TABLE curation_logs ADD COLUMN seo_status TEXT NOT NULL DEFAULT 'legacy'
  CHECK (seo_status IN ('legacy', 'ready', 'needs_review'));

CREATE INDEX idx_curation_logs_seo_status_published_at
  ON curation_logs (seo_status, published_at DESC);

CREATE INDEX idx_curation_logs_category_published_at
  ON curation_logs (category, published_at DESC);
